title: Deton Service
description: URL shortener on steroids.
github: [metadata]
encoding: UTF-8
theme: jekyll-theme-slate
kramdown:
  input: GFM
  hard_wrap: false
  future: true
  jailed: false
footer-links:
  github: e8kor
  linkedin: ikorniichuk
  twitter: e8kor